import type { Metadata } from "next";
import { Cormorant_Upright } from "next/font/google";
import { cn } from "@/lib/utils";

import AppHeader from "@/components/app-header";
import AppSidebar from "@/components/ui/sidebar/app-sidebar";
import Providers from "@/components/providers";

import { SidebarInset } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

const cormorantUpright = Cormorant_Upright({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "ÉGO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={cn("h-full font-mono antialiased", cormorantUpright.className)}
    >
      <body className="flex min-h-full flex-col">
        <Providers>
          <AppSidebar />

          <SidebarInset>
            <AppHeader />

            <main className="relative flex flex-1 flex-col">{children}</main>
            <Toaster />
          </SidebarInset>
        </Providers>
      </body>
    </html>
  );
}
